enigmaapi/apps/core/urls.py
#  Copyright (C) 2013  Authors, TALSOFT S.R.L.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# 
# TALSOFT S.R.L. - www.talsoft.com.ar - Mar del Plata, Argentina
# See the site of Enigma-gpg: http://www.enigmagpg.com

#from django.conf.urls.defaults import patterns, url
from django.conf.urls import patterns, url, include
from enigmaapi.apps.core import views 
from django.contrib import admin
from django.conf.urls import include
from django.views.generic.base import TemplateView


urlpatterns = patterns('enigmaapi.apps.core.views',
    url(r'^$', views.home, name='index'),
    url(r'^profile/', views.view_user_profile,name='userProfileView'),
    url(r'^user/invite/$',  views.view_form_invite_user,name='invite_user'),
    url(r'^user/invite/save/$',  views.activate_user,name='activate_invite_user'),
    url(r'^user/message/create/(\d+)/$',  views.view_form_message_create,name='message_create'),
    url(r'^user/message/decipher/$',  views.view_form_message_decipher_create,name='decipher_message_create'),
    url(r'^user/message/create/save$',  views.view_form_message_create,name='message_create_save'),
    url(r'^user/help/$', TemplateView.as_view(template_name="help.html"),name='help'), 
    url(r'^keymanager/password/request$',views.view_form_keypassword, name='request_keypassword'),
    url(r'^keymanager/password/complete', views.requestkey, name='requestkeypassword_complete'),
    url(r'^keymanager/password/forcerenew$', views.requestForceRenewKey, name='requestforcerenewkeys'),
    url(r'^keymanager/password/forcerenew/complete$', views.requestForceRenewKeyComplete, name='requestforcerenewkeyscomplete'),
    url(r'^accounts/profile/$', views.home, name='index'),
    url(r'^profile/save', views.save_profile,name='saveUserProfile'),
    #url(r'^search/keycontainer/$', views.ajax_keycontainer_search, name = 'keycontainer_search' ),
    #url(r'^search/keycontainer/getkey/(\d+)/$', views.ajax_get_keyPublic_userprofile, name = 'get_key_user' ),
)

enigmaapi/urls.py
#  Copyright (C) 2013  Authors, TALSOFT S.R.L.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# 
# TALSOFT S.R.L. - www.talsoft.com.ar - Mar del Plata, Argentina
# See the site of Enigma-gpg: http://www.enigmagpg.com

#from django.conf.urls import patterns, include, url
from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf.urls.static import static
from enigmaapi.apps.core.models import KeyContainer, UserProfile, InviteProfile
from enigmaapi.apps.core import views
from enigmaapi.apps.core.forms import RegistrationViewUniqueEmail
from django.contrib.auth import views as auth_views

admin.autodiscover()
admin.site.register(UserProfile)
admin.site.register(KeyContainer)
admin.site.register(InviteProfile)

from tastypie.api import Api
from api import UserResource,KeyContainerResource
 
v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(KeyContainerResource())


urlpatterns = patterns('',
    # Apps Core urls
    url(r'^',include('enigmaapi.apps.core.urls')),
    url(r'^oauth2/', include('provider.oauth2.urls', namespace = 'oauth2')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(v1_api.urls)),
     #override the default urls
    url(r'^accounts/password/change/$', auth_views.password_change, name='password_change'),
    url(r'^accounts/password/change/done/$',  auth_views.password_change_done,  name='password_change_done'),
    url(r'^accounts/password/reset/$', auth_views.password_reset,  name='password_reset'),
    url(r'^accounts/password/reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^accounts/password/reset/complete/$', auth_views.password_reset_complete,  name='password_reset_complete'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',  auth_views.password_reset_confirm, name='password_reset_confirm'),

    
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^user/invite/complete/$', TemplateView.as_view(template_name='invitation/invitation_complete.html'),name='complete_invite_user'),
#    (r'^accounts/', include('allauth.urls')),
    # Unique mail and username in register accounts and strong password
    url(r'^accounts/register', RegistrationViewUniqueEmail.as_view(), name='registration_register'),
)

enigmaapi/apps/core/forms.py
#  Copyright (C) 2013  Authors, TALSOFT S.R.L.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# 
# TALSOFT S.R.L. - www.talsoft.com.ar - Mar del Plata, Argentina
# See the site of Enigma-gpg: http://www.enigmagpg.com

from django import forms as forms
from enigmaapi.apps.core.models import UserProfile
from passwords.fields import PasswordField
from registration.backends.default.views import RegistrationView
from registration.forms import RegistrationFormUniqueEmail
from enigmaapi import settings


class SafeRegistrationForm( RegistrationFormUniqueEmail):
    
    bad_domains = [ 'mailinator.com','yopmail.com','filzmail.com','drdrb.com','mintemail.com','hushmail.com']
    
    def clean( self):
        """ Tests the password for dictionary attacks. """
        r = super( SafeRegistrationForm, self).clean()
        if r:
            import crack
            try:
                crack.VeryFascistCheck( self.cleaned_data[ 'password1'])
            except ValueError, message:
                raise forms.ValidationError("Please use a stronger password to protect your account. The current one is too weak")
            # Checkusername Min length
            try:
                username = self.cleaned_data.get('username')
                if username is not None and len(username) <= 4:
                    raise forms.ValidationError("Username must be at least 5 chars.")
            except ValueError, message:
                None
            # check mail service temporaly
            email_domain = self.data['email'].split('@')[1]
            if email_domain in self.bad_domains:
                raise forms.ValidationError("Registration using free email addresses is prohibited. Please supply a different email address.")
            if settings.DOMAIN_ALLOW_REGISTER is not "" and email_domain not in settings.DOMAIN_ALLOW_REGISTER:
                raise forms.ValidationError("Registration for that domain is prohibited. Please supply a different email address.")
            return r

class RegistrationViewUniqueEmail(RegistrationView):
    form_class = SafeRegistrationForm


class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    
    class Meta:
        model   = UserProfile
        exclude = ["user","email","date_joined","invited_user","membership","public_key","private_key","last_ip"]
    
   
    
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['class'] = 'inputform'
        self.fields['last_name'].widget.attrs['class'] = 'inputform'  
        self.fields['site'].widget.attrs['class'] = 'inputform'
        #self.fields['email'].widget.attrs['class'] = 'inputform'
        self.fields['company'].widget.attrs['class'] = 'inputform'
        self.fields['securitykeys'].widget.attrs['class'] = 'inputform'
        #self.fields['last_ip'].widget.attrs['class'] = 'inputform'  
    

class UserInviteForm(forms.Form):
    email = forms.EmailField
    

class UserMessageForm(forms.Form):
    email = forms.EmailField
    message = forms.Textarea

class UserDecipherMessageForm(forms.Form):
    keypassword = forms.PasswordInput
    message = forms.Textarea
        
class Request_passwordkey_form(forms.Form):
    keypassword =  PasswordField()

    
    
    

enigmaapi/templates/home/edit_userprofile.html
{% extends "registration/base.html" %}

{% load i18n %}
{% block content %}
<div class="containerbody"> 
  <h2 class="bluetitle">{% trans "User Profile" %}</h2>
   <div class="form">
		<form action="." method="POST">
		  {% csrf_token %}
			  {% for field in form %}
			  <div class="form-group">
			    {{ field.help_text }}
			    <div class="labelform">
			      {{ field.label_tag  }}
			    </div>  
			    {{field|escape }}
			    <div id="{{ field.auto_id }}_errors" class="error">
			      {{ field.errors }}
			    </div>
			  </div>
		  {% endfor %}
		  <div class="form-group">
		  	<input class="btn-download center" type="submit" value="Save" />
		  </div>
		</form>
	</div>
</div>
{% endblock %}

enigmaapi/templates/home/request_password_keyprivate_form.html
{% extends "registration/base.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"></div>{% endblock %}

{% block title %}{% trans "Password reset" %}{% endblock %}

{% block content %}
<div class="containerbody"> 
  <h2 class="bluetitle">{% trans "Password Keys" %}</h2>
<p><span style="font-size:12pt">{% trans "To configure your user profile, enter a password to generate your public and private key can decrypt the messages it receives. We do not store this password in our system, only you know."%} </br>{% trans "Note: the password must contain a minimum of 8 characters, 1 uppercase, 1 lowercase and 1 digit." %} </span></p>
 <div class="form">
	<form id="frm1" action="{% url 'requestkeypassword_complete' %}" method="POST">
		{% csrf_token %}
	<div class="form-group">
		{{ form.keypassword.errors }}
		{{ errorgenerate }}
	</div>
	<div class="form-group">
    
		<label for="id_keypassword" class="labelform">{% trans 'Key Password:' %}</label> 
		<input id="id_keypassword" class="inputform" maxlength="254" name="keypassword" type="password" />  
	</div>
	<div class="form-group">
		<input class="btn-download center" type="submit" value="{% trans 'Generate Keys' %}" />
	</div>
	</form>
</div>
</div>
{% endblock %}

enigmaapi/templates/home/request_password_keyprivate_form_force.html
{% extends "registration/base.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"></div>{% endblock %}

{% block title %}{% trans "Password reset" %}{% endblock %}

{% block content %}
<div class="containerbody"> 
  <h2 class="bluetitle">{% trans "Password Keys" %}</h2>
<p><span style="font-size:12pt">{% trans "To configure your user profile, enter a password to generate your public and private key can decrypt the messages it receives. We do not store this password in our system, only you know." %}</br>{% trans "Note: the password must contain a minimum of 8 characters, 1 uppercase, 1 lowercase and 1 digit." %} </span></p>
 <div class="form">
	<form id="frm1" action="{% url 'requestforcerenewkeyscomplete' %}" method="POST">
		{% csrf_token %}
	<div class="form-group">
		{{ form.keypassword.errors }}
		{{ errorgenerate }}
	</div>
	<div class="form-group">
    
		<label for="id_keypassword" class="labelform">{% trans 'Key Password:' %}</label> 
		<input id="id_keypassword" class="inputform" maxlength="254" name="keypassword" type="password" />  
	</div>
	<div class="form-group">
		<input class="btn-download center" type="submit" value="{% trans 'Generate Keys' %}" />
	</div>
	</form>
</div>
</div>
{% endblock %}