enigmaapi/apps/core/urls.py
#  Copyright (C) 2013  Authors, TALSOFT S.R.L.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# 
# TALSOFT S.R.L. - www.talsoft.com.ar - Mar del Plata, Argentina
# See the site of Enigma-gpg: http://www.enigmagpg.com

#from django.conf.urls.defaults import patterns, url
from django.conf.urls import patterns, url, include
from enigmaapi.apps.core import views 
from django.contrib import admin
from django.conf.urls import include
from django.views.generic.base import TemplateView


urlpatterns = patterns('enigmaapi.apps.core.views',
    url(r'^$', views.home, name='index'),
    url(r'^profile/', views.view_user_profile,name='userProfileView'),
    url(r'^user/invite/$',  views.view_form_invite_user,name='invite_user'),
    url(r'^user/invite/save/$',  views.activate_user,name='activate_invite_user'),
    url(r'^user/message/create/(\d+)/$',  views.view_form_message_create,name='message_create'),
    url(r'^user/message/decipher/$',  views.view_form_message_decipher_create,name='decipher_message_create'),
    url(r'^user/message/create/save$',  views.view_form_message_create,name='message_create_save'),
    url(r'^user/help/$', TemplateView.as_view(template_name="help.html"),name='help'), 
    url(r'^keymanager/password/request$',views.view_form_keypassword, name='request_keypassword'),
    url(r'^keymanager/password/complete', views.requestkey, name='requestkeypassword_complete'),
    url(r'^keymanager/password/forcerenew$', views.requestForceRenewKey, name='requestforcerenewkeys'),
    url(r'^keymanager/password/forcerenew/complete$', views.requestForceRenewKeyComplete, name='requestforcerenewkeyscomplete'),
    url(r'^accounts/profile/$', views.home, name='index'),
    url(r'^profile/save', views.save_profile,name='saveUserProfile'),
    #url(r'^search/keycontainer/$', views.ajax_keycontainer_search, name = 'keycontainer_search' ),
    #url(r'^search/keycontainer/getkey/(\d+)/$', views.ajax_get_keyPublic_userprofile, name = 'get_key_user' ),
)

enigmaapi/urls.py
#  Copyright (C) 2013  Authors, TALSOFT S.R.L.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# 
# TALSOFT S.R.L. - www.talsoft.com.ar - Mar del Plata, Argentina
# See the site of Enigma-gpg: http://www.enigmagpg.com

#from django.conf.urls import patterns, include, url
from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf.urls.static import static
from enigmaapi.apps.core.models import KeyContainer, UserProfile, InviteProfile
from enigmaapi.apps.core import views
from enigmaapi.apps.core.forms import RegistrationViewUniqueEmail
from django.contrib.auth import views as auth_views

admin.autodiscover()
admin.site.register(UserProfile)
admin.site.register(KeyContainer)
admin.site.register(InviteProfile)

from tastypie.api import Api
from api import UserResource,KeyContainerResource
 
v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(KeyContainerResource())


urlpatterns = patterns('',
    # Apps Core urls
    url(r'^',include('enigmaapi.apps.core.urls')),
    url(r'^oauth2/', include('provider.oauth2.urls', namespace = 'oauth2')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(v1_api.urls)),
     #override the default urls
    url(r'^accounts/password/change/$', auth_views.password_change, name='password_change'),
    url(r'^accounts/password/change/done/$',  auth_views.password_change_done,  name='password_change_done'),
    url(r'^accounts/password/reset/$', auth_views.password_reset,  name='password_reset'),
    url(r'^accounts/password/reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^accounts/password/reset/complete/$', auth_views.password_reset_complete,  name='password_reset_complete'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',  auth_views.password_reset_confirm, name='password_reset_confirm'),

    
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^user/invite/complete/$', TemplateView.as_view(template_name='invitation/invitation_complete.html'),name='complete_invite_user'),
#    (r'^accounts/', include('allauth.urls')),
    # Unique mail and username in register accounts and strong password
    url(r'^accounts/register', RegistrationViewUniqueEmail.as_view(), name='registration_register'),
)

enigmaapi/apps/core/forms.py
#  Copyright (C) 2013  Authors, TALSOFT S.R.L.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# 
# TALSOFT S.R.L. - www.talsoft.com.ar - Mar del Plata, Argentina
# See the site of Enigma-gpg: http://www.enigmagpg.com

from django import forms as forms
from enigmaapi.apps.core.models import UserProfile
from passwords.fields import PasswordField
from registration.backends.default.views import RegistrationView
from registration.forms import RegistrationFormUniqueEmail
from enigmaapi import settings


class SafeRegistrationForm( RegistrationFormUniqueEmail):
    
    bad_domains = [ 'mailinator.com','yopmail.com','filzmail.com','drdrb.com','mintemail.com','hushmail.com']
    
    def clean( self):
        """ Tests the password for dictionary attacks. """
        r = super( SafeRegistrationForm, self).clean()
        if r:
            import crack
            try:
                crack.VeryFascistCheck( self.cleaned_data[ 'password1'])
            except ValueError, message:
                raise forms.ValidationError("Please use a stronger password to protect your account. The current one is too weak")
            # Checkusername Min length
            try:
                username = self.cleaned_data.get('username')
                if username is not None and len(username) <= 4:
                    raise forms.ValidationError("Username must be at least 5 chars.")
            except ValueError, message:
                None
            # check mail service temporaly
            email_domain = self.data['email'].split('@')[1]
            if email_domain in self.bad_domains:
                raise forms.ValidationError("Registration using free email addresses is prohibited. Please supply a different email address.")
            if settings.DOMAIN_ALLOW_REGISTER is not "" and email_domain not in settings.DOMAIN_ALLOW_REGISTER:
                raise forms.ValidationError("Registration for that domain is prohibited. Please supply a different email address.")
            return r

class RegistrationViewUniqueEmail(RegistrationView):
    form_class = SafeRegistrationForm


class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    
    class Meta:
        model   = UserProfile
        exclude = ["user","email","date_joined","invited_user","membership","public_key","private_key","last_ip"]
    
   
    
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['class'] = 'inputform'
        self.fields['last_name'].widget.attrs['class'] = 'inputform'  
        self.fields['site'].widget.attrs['class'] = 'inputform'
        #self.fields['email'].widget.attrs['class'] = 'inputform'
        self.fields['company'].widget.attrs['class'] = 'inputform'
        self.fields['securitykeys'].widget.attrs['class'] = 'inputform'
        #self.fields['last_ip'].widget.attrs['class'] = 'inputform'  
    

class UserInviteForm(forms.Form):
    email = forms.EmailField
    

class UserMessageForm(forms.Form):
    email = forms.EmailField
    message = forms.Textarea

class UserDecipherMessageForm(forms.Form):
    keypassword = forms.PasswordInput
    message = forms.Textarea
        
class Request_passwordkey_form(forms.Form):
    keypassword =  PasswordField()

    
    
    

enigmaapi/templates/base.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
   <head>
       <meta charset="utf-8">
       <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
       <title>Secure Messaging Platform | Enigma GPG</title>
       <meta name="keywords" content="encrypt, messages, platform, secure, enigma, PRISM, SIBIOS, mobile, free, nsa">
	<meta name="description" content="EnigmaGPG Secure Messaging Platform, allows you to encrypt messages and files.">
       <meta name="viewport" content="width=1024">
	
       <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

       <link rel="stylesheet" href="{% static "registration/css/normalize.css" %}">
       <link rel="stylesheet" href="{% static "registration/css/main.css" %}">
       <script src="{% static "registration/js/vendor/modernizr-2.6.2.min.js" %}"></script>
   </head>
<body>
   <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
    <header class="site-header">
            <div class="site-header-container">
                <div class="site-logo"></div>
                <ul class="nav_main">
                	{% if user.is_authenticated %}
                   <li><a href="{% url 'index' %}">{% trans "Home" %}</a>  </li>
	               <li><a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a>  </li>
	               <li><a href="{% url 'auth_password_change' %}">{% trans "Change password" %}</a></li>
	           	   <li><a href="{% url 'userProfileView' %}">{{ user.username|escape }} </a></li>
	           	   <li><a href="{% url 'help' %}">{% trans "Help" %}</a>  </li>
	               {% else %}
	               <!--  <li><a href="{% url 'index' %}" data-ga-category="Pricing" data-ga-action="Pricing - top" data-ga-label=""> Pricing </a></li>-->
                   <li><a href="{% url 'auth_login' %}">{% trans "Log in" %}</a></li>
                   <li><a class="get_started_top" href="{% url 'registration_register' %}" data-ga-category="GetStarted" data-ga-action="GetStarted - top" data-ga-label=""> <strong>Get Started</strong></a></li>
	               {% endif %}
                   
                </ul>
            </div>
        </header>
    <div class="site-content">
	     <div class="containerbody"> 
	     {% if user.is_authenticated %}
				<p> <span style="font-size:10px"><b>{% trans "Last login" %}</b>: {{ user.last_login|escape }} <b>{% trans "Last IP" %}</b>: {{ userprofile.last_ip|escape }} <b>{% trans "Next Regeneration Keys" %}</b>: {{ daystoleft|escape }}  {% trans " days" %} - <a href="{% url 'requestforcerenewkeys' %}" >{% trans 'Renew Keys' %} </a> - <a href="https://bitbucket.org/enigmagpg/enigmagpg/issues?status=new&status=open" >{% trans 'Report an issue' %} </a> - {% trans 'BETA VERSION' %}</span> </p>
			{% endif %}
	        {% block content %}
	        
	        {% endblock %}
	        {% block content-related %}
	        {% endblock %}
	        
	      </div>
    </div>
    
    <footer class="site-footer" role="contentinfo"> 
       {% block footer %}
       <hr />
       {% endblock %}
        <div class="containerfooter"> 
             <p> 
                 <iframe allowtransparency="true" frameborder="0" scrolling="no" src="http://platform.twitter.com/widgets/tweet_button.1374787011.html#_=1375144400914&amp;count=none&amp;id=twitter-widget-0&amp;lang=en&amp;original_referer=http://enigmagpg.com&amp;size=l&amp;text= &amp;via=EnigmaGpg" class="twitter-share-button twitter-count-none" style="width: 77px; height: 28px; " title="Twitter Tweet Button" data-twttr-rendered="true"></iframe> 
                 &nbsp; 
                 
             </p> 
             EnigmaGPG ® 2013 Copyrights - <a href="http://www.talsoft.com.ar">Made in MDQ by Talsoft</a>. {% trans 'BETA VERSION' %} 
         </div> 
     </footer>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
      <!--  <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>-->
        <script src="{% static "registration/js/plugins.js" %}"></script>
        <script src="{% static "registration/js/main.js" %}"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
       <script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-42272716-1', 'enigmagpg.com');
	  ga('send', 'pageview');

	</script> 
 </body>

</html>

enigmaapi/templates/contact.html
{% extends "base.html" %}
{% load i18n %}
{% csrf_token %}
{% block content %}
<h1>Contact us</h1>
	<form action="{{ action }}" method="POST">
	 {% csrf_token %}
	<div class="fieldWrapper">
	{{ form.topic.errors }}
	<label for="id_topic">Kind of feedback:</label>
	{{ form.topic }}
	</div>
	<div class="fieldWrapper">
	{{ form.message.errors }}
	<label for="id_message">Your message:</label>
	{{ form.message }}
	</div>
	<div class="fieldWrapper">
	{{ form.sender.errors }}
	<label for="id_sender">Your email (optional):</label>
	{{ form.sender }}
	</div>
	<p><input type="submit" value="Submit"></p>

	</form>
{% endblock %}

enigmaapi/templates/help.html
{% extends "registration/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
{% if user.is_authenticated %}
<div class="containerbody" style="text-align: justify"> 

<h2>What Is EnigmaGPG for Bussines?</h2>
<p><span style="font-size:10pt;text-align: justify">
EnigmaGPG allows you to encrypt messages. Ensuring the authenticity, privacy and confidentiality of messages for your Business.<br>

<strong>Features:</strong><br>
- Allows communication messages private and confidential using public and private keys to encrypt and sign information.<br>
- Does not store messages. Manage your public and private keys centrally.<br>
- EnigmaGPG is a messenger platform simple, secure and user friendly for your business or friends.<br>
- Available for mobile devices through iOS and Android application.<br>
- Install, configure and manage a secure messaging platform for your business or group of friends.<br>
- Simple, Secure & Free Software.<br> </span></p>
<hr>
 <h2>{% trans "How to use?" %}</h2>
<p><span style="font-size:10pt;text-align: justify">
<strong>Steps:</strong><br>
1. Register Demo Live http://www.enigmagpg.com<br>
2. Login in and download extension browser.<br>
3. Invite contacts.<br>
<br>
<strong>Write a message:</strong><br>
1. Right-mouse click and go to Enigma GPG-> Cipher<br>
2. Select a contact and write a messages<br>
3. Copy and paste your cipher message in you gmail, facebook, o another web application.<br>
<br>
<strong>Read a message:</strong><br>
1. Right-mouse click and go to Enigma GPG-> Decipher<br>
2. Enter the Password.<br>
3. Paste message to Decipher EnigmaGPG.<br>
 </span>
</p>
<hr>
<h3>Design</h3>

<p><span style="font-size:10pt;text-align: justify">

The system consists of 2 EnigmaGpg modules respectively:<br>
- <strong>Daemon</strong>: This module is a web server that runs on the local network over HTTP/SSL. This takes care of exposing an API to Customer Module and interact with the system you have installed a browser addons.<br> 
- <strong>Customer Module</strong>: This module are extensions of browsers, in this case, there are modules for Chrome and Firefox. This module displays a graphical user interface, a contextual menu appears with the right mouse button, and communicates with the daemon for API to perform all system funcionalides.<br>
 </span></p>

 <h2>{% trans "What is GnuPG?" %}</h3>
 <p><span style="font-size:10pt;text-align: justify"> 
EnigmaGPG use GnuPG, it's a tool used to protect the privacy of the user in electronic communications. 
Protection exists only if the user can communicate with others and no one else can read the messages. 
GnuPG tries to ensure this privacy. It uses public key cryptography in which each user has a pair of keys. A pair of keys consists of a public key and a private key. A public key consists of the public portion of the master signing key, the public portions of the signing and encryption subkeys, and a set of user IDs that are used to associate the public key with a real person. Each of these parts contains data about itself. For a key, this data includes its ID, creation date, expiration date, etc . For a user identifier, this data includes the name of the person it identifies, an optional comment, and email address. The structure of the private key is similar, except that it contains only the private parts of the keys, and does not have the user ID information. 
Each user's private key is kept secret, it must not be revealed ever. The public key can be given to any person with whom the user wants to communicate.


 <h3>Encryption</h3>
</br>
<span style="font-size:10pt;text-align: justify">
Each user has a pair of keys: a public and a private. Each one has a specific role in the encryption and decryption of documents. You can think of a public key as a safety deposit box. When a sender encrypts a document using a public key, that document is put in the safe, the box closes, and the combination lock spun several times. The share of the private key, that is, the recipient, is the combination that can re-open the case and remove the paper. 
	Put it another way, only the person who owns the private key can retrieve a document encrypted using the associated public key encryption. 
	This model demonstrates the procedure for encrypting and decrypting documents in a very simple way. If the user wants to encrypt a message for Peter, it would use the public key of Peter, and Peter would decrypt it with his private key. </span></p>
	</br>
</span>
<hr>
 <h3>GnuPG FAQs</h3>
   <a href="FAQs http://www.gnupg.org/faq/gnupg-faq.html" >{% trans 'GnuPG FAQs' %}</a> </span></p>
<h3>Picking a good password</h3>
</br>
<span style="font-size:10pt;text-align: justify">
<p>EnigmaGPG use the GPG system for symmetric as well as asymmetric encryption schemes. Either method requires the use of a password or pass phrase. For a password containing uppercase and lowercase letters, digits, and special characters, 8-10 characters are sufficient for most users. This should *not* be your current CS password.</p>
<p>It is important if you use a 8-character password that you choose those characters randomly from the available typable characters on a standard keyboard (about 94). Assuming a cracker can brute-force check 100,000 passwords a second (doable on even a Pentium III), this is how long it would take (worst case scenario) to crack your password:</p>
<table>
<thead>
<tr><th >Letters available for password</th><th >Letters used in password</th><th >Time to crack</th></tr>
</thead>
<tbody>
<tr>
<td>26 (lowercase characters)</td>
<td>3</td>
<td>26<sup>3</sup>*.00001 = 0.18 seconds</td>
</tr>
<tr>
<td> </td>
<td>8</td>
<td>26<sup>8</sup>*.00001 = 2,088,271 seconds = 24.17 days</td>
</tr>
<tr>
<td>52 (English characters)</td>
<td>3</td>
<td>52<sup>3</sup>*.00001 = 1.4 seconds</td>
</tr>
<tr>
<td> </td>
<td>8</td>
<td>52<sup>8</sup>*.00001 = 534,597,285 seconds = 17 years</td>
</tr>
<tr>
<td>94 (keyboard characters)</td>
<td>3</td>
<td>94<sup>3</sup>*.00001 = 8.3 seconds</td>
</tr>
<tr>
<td> </td>
<td>8</td>
<td>94<sup>8</sup>*.00001 = 6.09*10<sup>10</sup> seconds = 1,933 years</td>
</tr>
</tbody>
</table>
<p>Naturally, the above supposes that the cracker only has one Pentium III system available. Even a small cluster of Core 2 Duo systems could cut the above times by a factor of about 25-100. Also, using a random key search, the cracker has a 50:50 chance of finding the password in half the time listed. As you can see, cracking an 8-character password consisting of all English language characters suddenly becomes quite feasible, taking maybe 1-3 months using a few fast systems. Brute-forcing a truly random 8-character password with the characters chosen from a pool of 94 would require the computing power equivalent of thousands of Pentium IIIs to succeed in an appreciable time. Using a 10 character password from a 94-character space would take over 17,000 millenia on a Pentium III and is unrealistic even using a large cluster of modern systems.</p>
</span>
<hr>
 <div class="grid"> 
    <div class="grid-cell"> 
        <h3><span class="star"><img src="{% static "registration/img/but1.png" %}"/>&nbsp;</span> Simple, Secure & beautiful</h3> 
        <p>Security is complex and unfriendly. But Enigma<br> is a messenger platform simple, secure and user friendly.</p> 
    </div> 
    <div class="grid-cell"> 
        <h3><span class="star"><img src="{% static "registration/img/but2.png" %}"/>&nbsp;</span> Data Encryption and Decryption</h3> 
        <p>Allows communication messages private and confidential using public and private keys to encrypt and sign information. <strong>Does not store messages and keys periodically renewed</strong>.</p> 
    </div> 
    <div class="grid-cell"> 
        <h3><span class="star"><img src="{% static "registration/img/but3.png" %}"/>&nbsp;</span> Mobile</h3> 
        <p>Available for mobile devices through iOS <br>and Android application.</p> 
    </div> 
    <div class="grid-cell"> 
        <h3><span class="star"><img src="{% static "registration/img/but4.png" %}"/>&nbsp;</span> API for developers</h3>
        <p>Developers can use Enigma API for create <br>secure Mobile, Web and Desktop Applications.</p> 
    </div> 
</div> 
</div>
{% endif %}
{% endblock %}

{% block footer %}
{% endblock %}

enigmaapi/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}

{% if user.is_authenticated %}
<div class="containerbody"> 
<hr>
<table width="100%">
	<tr>
		<td align="left">
		<span style="font-size:12pt">{% trans "Download the extension:       " %}</span>  <a class="btn-download" href="javascript:alert('Download your custom extension')" >{% trans 'Chrome' %} </a>  <a class="btn-download" href="javascript:alert('Download your custom extension')" >{% trans 'Firefox' %}</a>
		</td>
		<td align="right">
		<span style="font-size:12pt">{% trans "Invite a friend:       " %}</span><a class="btn-download" href="{% url 'invite_user' %}" >{% trans 'Invite User' %}</a>
		</td>
	</tr>
</table>
<hr>
<p class="downmessage">You need a customization for your business?</p>
              	<div class="downmessage">
             	 		<a class="btn-download" href="https://docs.google.com/a/talsoft.com.ar/spreadsheet/viewform?formkey=dFFuNkFzY3JFaEFrWXdEMDdIcm4xdmc6MA#gid=0" data-ga-category="GetStarted" data-ga-action="GetStarted - top" data-ga-label=""> <strong>Contact Us</strong></a>
              	</div>
              	
<!-- 	<table width="100%">
	<tr>
		<td>
			<span style="font-size:14pt"><strong>{% trans "Cipher a secure message without plugin" %}</strong></span>
		</td>
	</tr>
	<tr>
		<td>
			<p><span style="font-size:12pt"><strong>{% trans "Step 1- " %}</strong>{% trans "Write and Cipher a secure message:" %}</span></p>
			
		</td>
	</tr>
	<tr>
		<td>
			<p><span style="font-size:12pt"><strong>{% trans "Step 2- " %}</strong>{% trans "Copy the secure message and paste to send it to a web application, for example gmail, facebook,etc." %}</span></p>
		</td>
	</tr>
	<tr>
		<td>
		<hr>
			<span style="font-size:14pt"><strong>{% trans "Decrypt a secure message without plugin" %}</strong></span><a class="get_title" href="{% url 'decipher_message_create' %}" >{% trans 'Decrypt' %}</a>
		</td>
	</tr>
</table>-->
	<hr>
<strong>Steps:</strong><br>
1. Register http://www.enigmagpg.com<br>
2. Login in and download extension browser.<br>
3. Invite contacts.<br>
<br>
<strong>Write a message:</strong><br>
1. Right-mouse click and go to Enigma GPG-> Cipher<br>
2. Select a contact and write a messages<br>
3. Copy and paste your cipher message in you gmail, facebook, o another web application.<br>
<br>
<strong>Read a message:</strong><br>
1. Right-mouse click and go to Enigma GPG-> Decipher<br>
2. Enter the Password.<br>
3. Paste message to Decipher EnigmaGPG.<br>
 <hr>

 <div class="grid"> 
                    <div class="grid-cell"> 
                        <h3><span class="star"><img src="{% static "registration/img/but1.png" %}"/>&nbsp;</span> Simple, Secure & Free Software</h3> 
                        <p>EnigmaGPG is a messenger platform simple, secure and user friendly for your business or friends.<br> <strong>You can share, enhance, modify the source code for your business </strong>.</p> 
                    </div> 
                    <div class="grid-cell"> 
                        <h3><span class="star"><img src="{% static "registration/img/but2.png" %}"/>&nbsp;</span> Data Encryption and Decryption</h3> 
                        <p>Allows communication messages private and confidential using public and private keys to encrypt and sign information.<br> <strong>Does not store messages. Manage your public and private keys centrally.</strong></p> 
                    </div> 
                    <div class="grid-cell"> 
                        <h3><span class="star"><img src="{% static "registration/img/but3.png" %}"/>&nbsp;</span> Mobile</h3> 
                        <p>Available for mobile devices through iOS and Android application.</p> 
                    </div> 
                    <div class="grid-cell"> 
                        <h3><span class="star"><img src="{% static "registration/img/but4.png" %}"/>&nbsp;</span> Appliance EnigmaGPG</h3>
                        <p><strong>Install, configure and manage a secure messaging platform for your business </strong>or group of friends.</p> 
                    </div> 
                </div> 
</div>
{% endif %}
{% endblock %}

{% block footer %}
{% endblock %}

enigmaapi/templates/locked.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h3>Account locked: too many login attempts. Please try again later.</h3>
{% endblock %}

{% block footer %}
{% endblock %}